/**
 * Gestion de stock REST API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AdresseRequestDto {
  adresse1: string;
  adresse2: string;
  ville: string;
  codePostal: string;
  pays: string;
}

