/**
 * Gestion de stock REST API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CategorieResponseDto } from './categorieResponseDto';
import { EntrepriseResponseDto } from './entrepriseResponseDto';


export interface ArticleResponseDto { 
    id?: number;
    codeArticle?: string;
    designation?: string;
    prixUnitaire?: number;
    tauxTva?: number;
    prixUnitaireTtc?: number;
    photo?: string;
    categorie?: CategorieResponseDto;
    entreprise?: EntrepriseResponseDto;
}

