/**
 * Gestion de stock REST API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AdresseResponseDto } from './adresseResponseDto';
import { EntrepriseResponseDto } from './entrepriseResponseDto';


export interface ClientResponseDto { 
    id?: number;
    nom?: string;
    prenom?: string;
    adresse?: AdresseResponseDto;
    photo?: string;
    email?: string;
    numTel?: string;
    entreprise?: EntrepriseResponseDto;
}

