/**
 * Gestion de stock REST API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AdresseResponseDto } from './adresseResponseDto';


export interface EntrepriseResponseDto { 
    id?: number;
    nomEntreprise?: string;
    description?: string;
    photo?: string;
    email?: string;
    adresse?: AdresseResponseDto;
    codeFiscal?: string;
    numTel?: string;
    steWeb?: string;
    creationDate?: string;
}

