/**
 * Gestion de stock REST API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AdresseRequestDto } from './adresseRequestDto';

export interface EntrepriseRequestDto {
  nomEntreprise: string;
  description: string;
  email: string;
  adresse: AdresseRequestDto ;
  codeFiscal: string;
  numTel: string;
  steWeb: string;
  photo: string;
}


