/**
 * Gestion de stock REST API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ErrorDto { 
    httpCode?: number;
    errorCodes?: ErrorDto.ErrorCodesEnum;
    message?: string;
    errors?: Array<string>;
}
export namespace ErrorDto {
    export const ErrorCodesEnum = {
        ArticleNotFound: 'ARTICLE_NOT_FOUND',
        ArticleNotValid: 'ARTICLE_NOT_VALID',
        CategorieNotFound: 'CATEGORIE_NOT_FOUND',
        CategorieNotValid: 'CATEGORIE_NOT_VALID',
        EntrepriseNotFound: 'ENTREPRISE_NOT_FOUND',
        EntrepriseNotValid: 'ENTREPRISE_NOT_VALID',
        ClientNotFound: 'CLIENT_NOT_FOUND',
        ClientNotValid: 'CLIENT_NOT_VALID',
        FournisseurNotFound: 'FOURNISSEUR_NOT_FOUND',
        FournisseurNotValid: 'FOURNISSEUR_NOT_VALID',
        LigneCommandeClientNotFound: 'LIGNE_COMMANDE_CLIENT_NOT_FOUND',
        LigneCommandeClientNotValid: 'LIGNE_COMMANDE_CLIENT_NOT_VALID',
        LigneCommandeFournisseurNotFound: 'LIGNE_COMMANDE_FOURNISSEUR_NOT_FOUND',
        LigneCommandeFournisseurNotValid: 'LIGNE_COMMANDE_FOURNISSEUR_NOT_VALID',
        LigneVenteNotFound: 'LIGNE_VENTE_NOT_FOUND',
        LigneVenteNotValid: 'LIGNE_VENTE_NOT_VALID',
        MvtStkNotFound: 'MVT_STK_NOT_FOUND',
        MvtStkNotValid: 'MVT_STK_NOT_VALID',
        UtilisateurNotFound: 'UTILISATEUR_NOT_FOUND',
        UtilisateurNotValid: 'UTILISATEUR_NOT_VALID',
        CommandeClientNotFound: 'COMMANDE_CLIENT_NOT_FOUND',
        CommandeClientNotValid: 'COMMANDE_CLIENT_NOT_VALID',
        RolesNotFound: 'ROLES_NOT_FOUND',
        RolesNotValid: 'ROLES_NOT_VALID',
        CommandeFournisseurNotFound: 'COMMANDE_FOURNISSEUR_NOT_FOUND',
        CommandeFournisseurNotValid: 'COMMANDE_FOURNISSEUR_NOT_VALID',
        CategoryNotFound: 'CATEGORY_NOT_FOUND',
        CategoryNotValid: 'CATEGORY_NOT_VALID',
        UnsupportedMediaType: 'UNSUPPORTED_MEDIA_TYPE',
        VentesNotFound: 'VENTES_NOT_FOUND',
        VentesNotValid: 'VENTES_NOT_VALID',
        ImageFormatNotSupported: 'IMAGE_FORMAT_NOT_SUPPORTED'
    } as const;
    export type ErrorCodesEnum = typeof ErrorCodesEnum[keyof typeof ErrorCodesEnum];
}


