/**
 * Gestion de stock REST API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CommandeFournisseurResponseDto } from './commandeFournisseurResponseDto';
import { ArticleResponseDto } from './articleResponseDto';


export interface LigneCommandeFournisseurResponseDto { 
    id?: number;
    commandeFournisseur?: CommandeFournisseurResponseDto;
    article?: ArticleResponseDto;
    quantite?: number;
    prixUnitaire?: number;
    entrepriseId?: number;
}

