/**
 * Gestion de stock REST API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CommandeClientResponseDto } from './commandeClientResponseDto';
import { ArticleResponseDto } from './articleResponseDto';


export interface LigneCommandeClientResponseDto { 
    id?: number;
    commandeClient?: CommandeClientResponseDto;
    article?: ArticleResponseDto;
    quantite?: number;
    prixUnitaire?: number;
    entrepriseId?: number;
}

