/**
 * Gestion de stock REST API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { VentesResponseDto } from './ventesResponseDto';
import { ArticleResponseDto } from './articleResponseDto';


export interface LigneVenteResponseDto { 
    id?: number;
    vente?: VentesResponseDto;
    article?: ArticleResponseDto;
    quantite?: number;
    prixUnitaire?: number;
    entrepriseId?: number;
}

