/**
 * Gestion de stock REST API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface MvtStkRequestDto { 
    dateMvt?: string;
    quantite?: number;
    typeMvt?: MvtStkRequestDto.TypeMvtEnum;
    articleId?: number;
    entrepriseId?: number;
}
export namespace MvtStkRequestDto {
    export const TypeMvtEnum = {
        Entree: 'ENTREE',
        Sortie: 'SORTIE'
    } as const;
    export type TypeMvtEnum = typeof TypeMvtEnum[keyof typeof TypeMvtEnum];
}


