/**
 * Gestion de stock REST API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ArticleResponseDto } from './articleResponseDto';


export interface MvtStkResponseDto { 
    id?: number;
    dateMvt?: string;
    quantite?: number;
    typeMvt?: MvtStkResponseDto.TypeMvtEnum;
    article?: ArticleResponseDto;
    entrepriseId?: number;
}
export namespace MvtStkResponseDto {
    export const TypeMvtEnum = {
        Entree: 'ENTREE',
        Sortie: 'SORTIE'
    } as const;
    export type TypeMvtEnum = typeof TypeMvtEnum[keyof typeof TypeMvtEnum];
}


