/**
 * Gestion de stock REST API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface RegisterRequestDto { 
    username?: string;
    email?: string;
    password?: string;
    nom?: string;
    prenom?: string;
    role?: string;
    entrepriseId?: number;
}

