/**
 * Gestion de stock REST API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UtilisateurResponseDto } from './utilisateurResponseDto';


export interface RolesResponseDto { 
    id?: number;
    roleName?: string;
    utilisateur?: UtilisateurResponseDto;
    entrepriseId?: number;
}

