/**
 * Gestion de stock REST API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RolesResponseDto } from './rolesResponseDto';
import { AdresseResponseDto } from './adresseResponseDto';
import { EntrepriseResponseDto } from './entrepriseResponseDto';


export interface UtilisateurResponseDto { 
    id?: number;
    nom?: string;
    prenom?: string;
    email?: string;
    dateDeNaissance?: string;
    motDePasse?: string;
    photo?: string;
    entrepriseId?: number;
    entreprise?: EntrepriseResponseDto;
    adresse?: AdresseResponseDto;
    roles?: Array<RolesResponseDto>;
}

