/**
 * Gestion de stock REST API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { LigneVenteResponseDto } from './ligneVenteResponseDto';


export interface VentesResponseDto { 
    id?: number;
    code?: string;
    dateVente?: string;
    commentaire?: string;
    entrepriseId?: number;
    ligneVentes?: Array<LigneVenteResponseDto>;
}

