export * from './articleController.service';
import { ArticleControllerService } from './articleController.service';
export * from './authController.service';
import { AuthControllerService } from './authController.service';
export * from './categorieController.service';
import { CategorieControllerService } from './categorieController.service';
export * from './clientController.service';
import { ClientControllerService } from './clientController.service';
export * from './commandeClientController.service';
import { CommandeClientControllerService } from './commandeClientController.service';
export * from './commandeFournisseurController.service';
import { CommandeFournisseurControllerService } from './commandeFournisseurController.service';
export * from './entrepriseController.service';
import { EntrepriseControllerService } from './entrepriseController.service';
export * from './fournisseurController.service';
import { FournisseurControllerService } from './fournisseurController.service';
export * from './mvtStkController.service';
import { MvtStkControllerService } from './mvtStkController.service';
export * from './rolesController.service';
import { RolesControllerService } from './rolesController.service';
export * from './utilisateurController.service';
import { UtilisateurControllerService } from './utilisateurController.service';
export * from './ventesController.service';
import { VentesControllerService } from './ventesController.service';
export const APIS = [ArticleControllerService, AuthControllerService, CategorieControllerService, ClientControllerService, CommandeClientControllerService, CommandeFournisseurControllerService, EntrepriseControllerService, FournisseurControllerService, MvtStkControllerService, RolesControllerService, UtilisateurControllerService, VentesControllerService];
